// Seed: Customers (50 diverse customers - all business types & loyalty statuses)
const { v4: uuidv4 } = require('uuid');

module.exports = async function seedCustomers(db, { log }) {
  log('Seeding customers (50 diverse customers - all business types & loyalty statuses)...');

  const customers = [
    // CORPORATE - VIP (High value)
    {
      id: uuidv4(),
      name: 'PT. Maju Bersama Indonesia',
      email: 'procurement@majubersama.co.id',
      phone: '+62-21-5551234',
      business_type: 'corporate',
      loyalty_status: 'vip',
      total_orders: 85,
      total_spent: 850000000,
    },
    {
      id: uuidv4(),
      name: 'PT. Bank Nasional Indonesia',
      email: 'corporate@bni.co.id',
      phone: '+62-21-5552345',
      business_type: 'corporate',
      loyalty_status: 'vip',
      total_orders: 120,
      total_spent: 1200000000,
    },
    {
      id: uuidv4(),
      name: 'PT. Telekomunikasi Indonesia',
      email: 'events@telkom.co.id',
      phone: '+62-21-5553456',
      business_type: 'corporate',
      loyalty_status: 'vip',
      total_orders: 95,
      total_spent: 950000000,
    },
    {
      id: uuidv4(),
      name: 'PT. Pertamina',
      email: 'procurement@pertamina.com',
      phone: '+62-21-5554567',
      business_type: 'corporate',
      loyalty_status: 'vip',
      total_orders: 78,
      total_spent: 780000000,
    },
    {
      id: uuidv4(),
      name: 'PT. Garuda Indonesia',
      email: 'corporate.gift@garuda.co.id',
      phone: '+62-21-5555678',
      business_type: 'corporate',
      loyalty_status: 'vip',
      total_orders: 65,
      total_spent: 650000000,
    },

    // CORPORATE - Regular
    {
      id: uuidv4(),
      name: 'PT. Startup Digital',
      email: 'hello@startupdigital.id',
      phone: '+62-21-5556789',
      business_type: 'corporate',
      loyalty_status: 'regular',
      total_orders: 12,
      total_spent: 48000000,
    },
    {
      id: uuidv4(),
      name: 'CV. Usaha Mandiri',
      email: 'admin@usahamandiri.co.id',
      phone: '+62-21-5557890',
      business_type: 'corporate',
      loyalty_status: 'regular',
      total_orders: 8,
      total_spent: 32000000,
    },
    {
      id: uuidv4(),
      name: 'PT. Konsultan Jaya',
      email: 'info@konsultanjaya.com',
      phone: '+62-21-5558901',
      business_type: 'corporate',
      loyalty_status: 'regular',
      total_orders: 15,
      total_spent: 60000000,
    },

    // CORPORATE - New
    {
      id: uuidv4(),
      name: 'PT. Baru Berdiri',
      email: 'info@baruberdiri.com',
      phone: '+62-21-5559012',
      business_type: 'corporate',
      loyalty_status: 'new',
      total_orders: 1,
      total_spent: 5000000,
    },
    {
      id: uuidv4(),
      name: 'CV. Fresh Start',
      email: 'contact@freshstart.id',
      phone: '+62-21-5550123',
      business_type: 'corporate',
      loyalty_status: 'new',
      total_orders: 0,
      total_spent: 0,
    },

    // WEDDING - VIP (Frequent wedding organizers)
    {
      id: uuidv4(),
      name: 'Wedding Organizer Bintang',
      email: 'info@weddingbintang.com',
      phone: '+62-21-8881234',
      business_type: 'wedding',
      loyalty_status: 'vip',
      total_orders: 150,
      total_spent: 1500000000,
    },
    {
      id: uuidv4(),
      name: 'Elegant Wedding Planner',
      email: 'contact@elegantwedding.id',
      phone: '+62-21-8882345',
      business_type: 'wedding',
      loyalty_status: 'vip',
      total_orders: 130,
      total_spent: 1300000000,
    },
    {
      id: uuidv4(),
      name: 'Royal Wedding Jakarta',
      email: 'royal@royalwedding.co.id',
      phone: '+62-21-8883456',
      business_type: 'wedding',
      loyalty_status: 'vip',
      total_orders: 110,
      total_spent: 1100000000,
    },

    // WEDDING - Regular
    {
      id: uuidv4(),
      name: 'Dream Wedding Jakarta',
      email: 'hello@dreamwedding.co.id',
      phone: '+62-21-8884567',
      business_type: 'wedding',
      loyalty_status: 'regular',
      total_orders: 25,
      total_spent: 125000000,
    },
    {
      id: uuidv4(),
      name: 'Simple Wedding Planner',
      email: 'simple@simplewedding.id',
      phone: '+62-21-8885678',
      business_type: 'wedding',
      loyalty_status: 'regular',
      total_orders: 18,
      total_spent: 90000000,
    },

    // EVENT - VIP
    {
      id: uuidv4(),
      name: 'Event Organizer Prima',
      email: 'info@eoprima.com',
      phone: '+62-21-7771234',
      business_type: 'event',
      loyalty_status: 'vip',
      total_orders: 88,
      total_spent: 440000000,
    },
    {
      id: uuidv4(),
      name: 'Corporate Event Solutions',
      email: 'events@ces.co.id',
      phone: '+62-21-7772345',
      business_type: 'event',
      loyalty_status: 'vip',
      total_orders: 72,
      total_spent: 360000000,
    },

    // EVENT - Regular & New
    {
      id: uuidv4(),
      name: 'Party Planner Jakarta',
      email: 'party@ppj.id',
      phone: '+62-21-7773456',
      business_type: 'event',
      loyalty_status: 'regular',
      total_orders: 20,
      total_spent: 100000000,
    },
    {
      id: uuidv4(),
      name: 'New Event Organizer',
      email: 'new@neweo.com',
      phone: '+62-21-7774567',
      business_type: 'event',
      loyalty_status: 'new',
      total_orders: 2,
      total_spent: 10000000,
    },

    // INDIVIDUAL - VIP (Frequent personal buyers)
    {
      id: uuidv4(),
      name: 'Keluarga Tanoto',
      email: 'tanoto.family@gmail.com',
      phone: '+62-812-5555-6666',
      business_type: 'individual',
      loyalty_status: 'vip',
      total_orders: 45,
      total_spent: 225000000,
    },
    {
      id: uuidv4(),
      name: 'Keluarga Wijaya',
      email: 'family.wijaya@gmail.com',
      phone: '+62-818-9876-5432',
      business_type: 'individual',
      loyalty_status: 'vip',
      total_orders: 38,
      total_spent: 190000000,
    },

    // INDIVIDUAL - Regular
    {
      id: uuidv4(),
      name: 'Bapak Hendro Susilo',
      email: 'hendro.s@outlook.com',
      phone: '+62-857-9999-8888',
      business_type: 'individual',
      loyalty_status: 'regular',
      total_orders: 8,
      total_spent: 40000000,
    },
    {
      id: uuidv4(),
      name: 'Ibu Sri Wahyuni',
      email: 'sri.wahyuni@yahoo.com',
      phone: '+62-812-3333-4444',
      business_type: 'individual',
      loyalty_status: 'regular',
      total_orders: 5,
      total_spent: 25000000,
    },
    {
      id: uuidv4(),
      name: 'Bapak Agus Setiawan',
      email: 'agus.setiawan@gmail.com',
      phone: '+62-813-7777-8888',
      business_type: 'individual',
      loyalty_status: 'regular',
      total_orders: 6,
      total_spent: 30000000,
    },

    // INDIVIDUAL - New
    {
      id: uuidv4(),
      name: 'Ibu Ratna Dewi',
      email: 'ratna.dewi88@gmail.com',
      phone: '+62-813-1234-5678',
      business_type: 'individual',
      loyalty_status: 'new',
      total_orders: 1,
      total_spent: 5000000,
    },
    {
      id: uuidv4(),
      name: 'First Time Buyer',
      email: 'newbuyer@gmail.com',
      phone: '+62-812-0000-0001',
      business_type: 'individual',
      loyalty_status: 'new',
      total_orders: 0,
      total_spent: 0,
    },
    {
      id: uuidv4(),
      name: 'Potential Customer',
      email: 'potential@gmail.com',
      phone: '+62-812-0000-0002',
      business_type: 'individual',
      loyalty_status: 'new',
      total_orders: 0,
      total_spent: 0,
    },

    // EDGE CASES
    {
      id: uuidv4(),
      name: 'Customer Without Email',
      email: null,
      phone: '+62-812-9999-0001',
      business_type: 'individual',
      loyalty_status: 'regular',
      total_orders: 3,
      total_spent: 15000000,
    },
    {
      id: uuidv4(),
      name: 'Customer Without Phone',
      email: 'nophone.customer@gmail.com',
      phone: null,
      business_type: 'individual',
      loyalty_status: 'regular',
      total_orders: 2,
      total_spent: 10000000,
    },
    {
      id: uuidv4(),
      name: 'Very Long Customer Name That Tests The Character Limits Of The Database Field',
      email: 'longname@test.com',
      phone: '+62-812-9999-0003',
      business_type: 'corporate',
      loyalty_status: 'new',
      total_orders: 1,
      total_spent: 5000000,
    },
    {
      id: uuidv4(),
      name: "Customer O'Brien & Sons, Ltd.",
      email: 'obrien@test.com',
      phone: '+62-812-9999-0004',
      business_type: 'corporate',
      loyalty_status: 'regular',
      total_orders: 4,
      total_spent: 20000000,
    },
    {
      id: uuidv4(),
      name: 'Customer With Unicode: \u65E5\u672C\u8A9E\u30C6\u30B9\u30C8',
      email: 'unicode@test.com',
      phone: '+62-812-9999-0005',
      business_type: 'individual',
      loyalty_status: 'new',
      total_orders: 1,
      total_spent: 5000000,
    },

    // More variety for testing filters
    {
      id: uuidv4(),
      name: 'Yayasan Pendidikan Nusantara',
      email: 'admin@ypnusantara.org',
      phone: '+62-274-1234567',
      business_type: 'event',
      loyalty_status: 'regular',
      total_orders: 12,
      total_spent: 48000000,
    },
    {
      id: uuidv4(),
      name: 'Rumah Sakit Kasih Ibu',
      email: 'humas@rskasihibu.or.id',
      phone: '+62-21-6661234',
      business_type: 'corporate',
      loyalty_status: 'vip',
      total_orders: 35,
      total_spent: 175000000,
    },
    {
      id: uuidv4(),
      name: 'Gereja HKBP Jakarta',
      email: 'sekretariat@hkbpjakarta.or.id',
      phone: '+62-21-6662345',
      business_type: 'event',
      loyalty_status: 'regular',
      total_orders: 18,
      total_spent: 72000000,
    },
    {
      id: uuidv4(),
      name: 'Kementerian BUMN',
      email: 'protokol@bumn.go.id',
      phone: '+62-21-5001234',
      business_type: 'corporate',
      loyalty_status: 'vip',
      total_orders: 55,
      total_spent: 550000000,
    },

    // Additional for comprehensive testing
    {
      id: uuidv4(),
      name: 'Gift Shop Central',
      email: 'central.giftshop@yahoo.com',
      phone: '+62-31-9991234',
      business_type: 'corporate',
      loyalty_status: 'regular',
      total_orders: 22,
      total_spent: 88000000,
    },
    {
      id: uuidv4(),
      name: 'Hampers Jakarta Store',
      email: 'hampers@jakartastore.com',
      phone: '+62-21-9992345',
      business_type: 'corporate',
      loyalty_status: 'regular',
      total_orders: 19,
      total_spent: 76000000,
    },
    {
      id: uuidv4(),
      name: 'Souvenir Murah',
      email: 'souvenirmurah@gmail.com',
      phone: '+62-21-9993456',
      business_type: 'individual',
      loyalty_status: 'regular',
      total_orders: 7,
      total_spent: 28000000,
    },
    {
      id: uuidv4(),
      name: 'Toko Kado Indah',
      email: 'tokokadoindah@gmail.com',
      phone: '+62-22-7772345',
      business_type: 'individual',
      loyalty_status: 'regular',
      total_orders: 9,
      total_spent: 36000000,
    },

    // High-value single transactions
    {
      id: uuidv4(),
      name: 'Mega Corporation Order',
      email: 'mega@megacorp.com',
      phone: '+62-21-1111111',
      business_type: 'corporate',
      loyalty_status: 'vip',
      total_orders: 5,
      total_spent: 500000000,
    },

    // Zero activity customers
    {
      id: uuidv4(),
      name: 'Inactive Customer 1',
      email: 'inactive1@test.com',
      phone: '+62-812-0000-1001',
      business_type: 'individual',
      loyalty_status: 'new',
      total_orders: 0,
      total_spent: 0,
    },
    {
      id: uuidv4(),
      name: 'Inactive Customer 2',
      email: 'inactive2@test.com',
      phone: '+62-812-0000-1002',
      business_type: 'corporate',
      loyalty_status: 'new',
      total_orders: 0,
      total_spent: 0,
    },

    // International format phones
    {
      id: uuidv4(),
      name: 'International Customer',
      email: 'intl@customer.com',
      phone: '+1-555-123-4567',
      business_type: 'corporate',
      loyalty_status: 'regular',
      total_orders: 3,
      total_spent: 15000000,
    },
    {
      id: uuidv4(),
      name: 'Singapore Customer',
      email: 'sg@customer.com',
      phone: '+65-9123-4567',
      business_type: 'corporate',
      loyalty_status: 'regular',
      total_orders: 4,
      total_spent: 20000000,
    },

    // Additional wedding customers
    {
      id: uuidv4(),
      name: 'Budget Wedding Planner',
      email: 'budget@wedding.id',
      phone: '+62-21-8886789',
      business_type: 'wedding',
      loyalty_status: 'new',
      total_orders: 3,
      total_spent: 15000000,
    },
    {
      id: uuidv4(),
      name: 'Premium Wedding Service',
      email: 'premium@wedding.id',
      phone: '+62-21-8887890',
      business_type: 'wedding',
      loyalty_status: 'vip',
      total_orders: 60,
      total_spent: 600000000,
    },

    // More event organizers
    {
      id: uuidv4(),
      name: 'Birthday Party Specialist',
      email: 'birthday@party.id',
      phone: '+62-21-7775678',
      business_type: 'event',
      loyalty_status: 'regular',
      total_orders: 30,
      total_spent: 90000000,
    },
    {
      id: uuidv4(),
      name: 'Corporate Gathering Pro',
      email: 'gathering@pro.id',
      phone: '+62-21-7776789',
      business_type: 'event',
      loyalty_status: 'vip',
      total_orders: 50,
      total_spent: 250000000,
    },

    // Final customers
    {
      id: uuidv4(),
      name: 'Last Customer Entry',
      email: 'last@customer.com',
      phone: '+62-812-9999-9999',
      business_type: 'individual',
      loyalty_status: 'new',
      total_orders: 0,
      total_spent: 0,
    },
  ];

  const insertCustomer = db.prepare(
    `INSERT INTO customers (id, name, email, phone, business_type, loyalty_status, total_orders, total_spent) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
  );
  customers.forEach((c) =>
    insertCustomer.run(
      c.id,
      c.name,
      c.email,
      c.phone,
      c.business_type,
      c.loyalty_status,
      c.total_orders,
      c.total_spent
    )
  );
  log(`   Created ${customers.length} customers`);

  return { customers };
};
